name: Super-Linter

on: push            

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Super-Linter
        uses: super-linter/super-linter@v7.1.0 

      - name: Format code with Prettier
        uses: prettier/action
        with:
          args: --write

        env: 
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
